# This is a basic workflow to help you get started with Actions

name: WORKFLOW-CALLING-OTHER-WORKFLOW

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      workflow-input-1:
        description: 'workflow-input-1'
        required: true
        default: ''
      workflow-input-2:
        description: 'workflow-input-2'
        required: true
        default: ''


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "FEATURE BRANCHHH --- ${{ inputs.workflow-input-1 }}-${{ inputs.workflow-input-2 }}"

      - name: Trigger Workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'workflow-being-called.yml',
              ref: 'joshjohanning-feature-branch',
              inputs: {
                "workflow-input-1": "value-1",
                "workflow-input-2": "value-2",
              }
            })
